routes/web.php
	array('as' => 'wines', 'uses' => 'IndexController@redirect_wines'));*/

Route::group(array('middleware' => 'minificar', 'prefix' => LaravelLocalization::setLocale()), function(){
//Route::group(array('prefix' => LaravelLocalization::setLocale()), function(){
	Route::get('/', array('as' => '/', 'uses' => 'IndexController@index'));
	Route::get('politicas_cookies', array('as' => 'politicas_cookies', 'uses' => 'IndexController@politicas_cookies'));
	Route::get('politicas_privacidad', array('as' => 'politicas_privacidad', 'uses' => 'IndexController@politicas_privacidad'));

	Route::get(LaravelLocalization::transRoute('route.route_index'), 
		array('as' => 'routes.index', 'uses' => 'Routes\RoutesWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.route_show'), 
		array('as' => 'routes.show', 'uses' => 'Routes\RoutesWebController@show'));

	Route::get(LaravelLocalization::transRoute('route.search'), 
		array('as' => 'search', 'uses' => 'Plans\PlansWebController@search'));

	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-index'), 
		array('as' => 'enotourism-mallorca.events.index', 'uses' => 'Events\EventsWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-map'), 
		array('as' => 'enotourism-mallorca.events.map', 'uses' => 'Events\EventsWebController@map'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-create'), 
		array('as' => 'enotourism-mallorca.events.create', 'uses' => 'Events\EventsWebController@create'));
	Route::post(LaravelLocalization::transRoute('route.enotourism-mallorca-store'), 
		array('as' => 'enotourism-mallorca.events.store', 'uses' => 'Events\EventsWebController@store'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-show_event'), 
		array('as' => 'enotourism-mallorca.events.show', 'uses' => 'Events\EventsWebController@show'));


	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-gift'), 
		array('as' => 'enotourism-mallorca.gift', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-dis'), 
		array('as' => 'enotourism-mallorca.dis', 'uses' => 'Plans\PlansWebController@index_dis'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-user'), 
		array('as' => 'enotourism-mallorca.user', 'uses' => 'Users\UsersWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-item'), 
		array('as' => 'enotourism-mallorca.item', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-cat'), 
		array('as' => 'enotourism-mallorca.cat', 'uses' => 'Plans\PlansWebController@index_cat'));

	Route::any('orders/confirm_visit/{order_encrypted}/{set?}', array('as' => 'orders.confirm_visit', 
		'uses' => 'Orders\OrdersWebController@confirm_visit'));
	Route::any('orders/confirm_payment/{crypt}/{set?}', array('as' => 'orders.confirm_payment', 
		'uses' => 'Orders\OrdersWebController@confirm_payment'));
	Route::post('plans/stocks/get_time', array('as' => 'plans.stocks.get_time', 'uses' => 'PlansStocks\PlansStocksWebController@get_time'));
	Route::post('orders/get_time', array('as' => 'orders.get_time', 
		'uses' => 'Orders\OrdersPanelController@get_time'));
	Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
		['only' => ['store', 'update', 'destroy'], 'as' => 'events']);

	Route::any('plans/comment', array('as' => 'plans.comment', 'uses' => 'Plans\PlansWebController@comment'));

	Route::any('cart', array('as' => 'orders.index', 'uses' => 'Orders\OrdersWebController@index'));
	Route::post('cart/update', array('as' => 'orders.update', 'uses' => 'Orders\OrdersWebController@update'));
	Route::get('add_to_cart', array('as' => 'orders.add_to_cart', 'uses' => 'Orders\OrdersWebController@add_to_cart'));
	Route::get('orders/{code}/{email}', array('as' => 'orders.show', 'uses' => 'Orders\OrdersWebController@show'));
	Route::post('cart/save', array('as' => 'orders.save', 'uses' => 'Orders\OrdersWebController@save'));
	Route::get('cart/delete/{id}', array('as' => 'orders.delete', 'uses' => 'Orders\OrdersWebController@delete'));
	Route::get('cart/coupon/{coupons_id?}', array('as' => 'orders.coupon', 'uses' => 'Orders\OrdersWebController@coupon'));
	Route::get('cart/callback/{id}', array('as' => 'orders.callback', 'uses' => 'Orders\OrdersWebController@callback'));

	Route::get('temp_image_png', array('as' => 'index.temp_image_png', 'uses' => 'IndexController@temp_image_png'));

});

Auth::routes();
Imgfly::routes();

Route::get('back/orders/download_voucher/{orders_id}/{email}', 
	array('as' => 'back.orders.download_voucher', 'uses' => 'Orders\OrdersPanelController@download_voucher'));


Route::group(array('middleware' => 'auth'), function(){

	Route::get('back', 'HomeController@index')->name('back');

	Route::group(array('prefix' => 'back'), function(){

		Route::group(array('middleware' => 'admin'), function(){

			Route::resource('labels/langs', 'LabelsLangs\LabelsLangsController', 
				['only' => ['update'], 'as' => 'back.labels']);

			Route::resource('labels', 'Labels\LabelsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		});

		Route::group(array('middleware' => 'notuser'), function(){

			Route::resource('plans/stocks', 'PlansStocks\PlansStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);
			Route::get('plans/stocks/{items_id}', 
				array('as' => 'back.plans.stocks.show', 'uses' => 'PlansStocks\PlansStocksPanelController@show'));
				
			Route::resource('plans/photos', 'PlansPhotos\PlansPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);

			Route::resource('plans', 'Plans\PlansPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
            Route::get('plans/action/promoted/{item}', 
                array('as' => 'back.plans.promoted.toggle', 'uses' => 'Plans\PlansPanelController@toggle_promoted'));

			Route::resource('events/stocks', 'EventsStocks\EventsStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/stocks/{items_id}', 
				array('as' => 'back.events.stocks.show', 'uses' => 'EventsStocks\EventsStocksPanelController@show'));

			Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/photos/destroy/{photo}', 
				array('as' => 'back.events.photos.destroy', 'uses' => 'EventsPhotos\EventsPhotosPanelController@destroy'));

			Route::get('events/instagram/get/{item}', array('as' => 'back.events.instagram.get', 'uses' => 'Events\EventsPanelController@instagram_get'));
			Route::get('events/translate/{item}', array('as' => 'back.events.translate', 'uses' => 'Events\EventsPanelController@translate'));

			Route::resource('events', 'Events\EventsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::resource('packs/photos', 'PacksPhotos\PacksPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.packs']);
			Route::get('packs/photos/destroy/{photo}', 
				array('as' => 'back.packs.photos.destroy', 'uses' => 'PacksPhotos\PacksPhotosPanelController@destroy'));

			Route::any('packs/additems/{items_id}', 
				array('as' => 'back.plans.additems', 'uses' => 'Packs\PacksPanelController@additems'));

			Route::get('packs/translate/{item}', array('as' => 'back.packs.translate', 'uses' => 'Packs\PacksPanelController@translate'));
			Route::resource('packs', 'Packs\PacksPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::get('blogs/translate/{blog}', array('as' => 'back.blogs.translate', 'uses' => 'Routes\RoutesPanelController@translate'));
			Route::resource('blogs/photos', 'BlogsPhotos\BlogsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.blogs']);
			Route::get('blogs/photos/destroy/{photo}', 
				array('as' => 'back.blogs.photos.destroy', 'uses' => 'BlogsPhotos\BlogsPhotosPanelController@destroy'));
			Route::resource('routes', 'Routes\RoutesPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

			Route::get('users/action/promoted/{item}', 
				array('as' => 'back.users.promoted.toggle', 'uses' => 'Users\UsersPanelController@toggle_promoted'));

		});


		Route::resource('coupons', 'Coupons\CouponsPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		Route::resource('users/photos', 'UsersPhotos\UsersPhotosPanelController', 
			['only' => ['store', 'update', 'destroy'], 'as' => 'back.users']);

		Route::resource('users', 'Users\UsersPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


		Route::resource('orders', 'Orders\OrdersPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
		Route::get('back/orders/mark_booking/{order}/{action}', 
			array('as' => 'back.orders.mark_booking', 'uses' => 'Orders\OrdersPanelController@mark_booking'));
		/*Route::post('locations/get_districts', array('as' => 'back.locations.get_districts', 'uses' => 'Locations\LocationsPanelController@get_districts'));*/

	});
	
});


Route::get('sitemap', array('as' => 'sitemap', 'uses' => 'SitemapController@index'));
Route::get('/sitemap-plans.xml', array('as' => 'sitemap-plans', 'uses' => 'SitemapController@plans'));
Route::get('/sitemap-users.xml', array('as' => 'sitemap-users', 'uses' => 'SitemapController@users'));

app/Http/Controllers/Packs/PacksPanelController.php
<?php

namespace App\Http\Controllers\Packs;

use App\Items;
use App\ItemsPacks;
use Illuminate\Http\Request;

class PacksPanelController extends PacksController
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['query'] = parent::_index([]);
        if(\Auth::user()->isAdmin()){
            $this->data['users_lov'] = \App\User::whereHas('plans', function ($query) {
                    $query->where('status', '=', 'active');
                })->pluck('name', 'id')->all();
        }
        $this->data['labels_lov'] = \App\Labels::whereHas('plans', function ($query) {
                $query->where('status', '=', 'active');
            })->listsTranslations('title')->pluck('title', 'id')->all();
        $this->data['status_lov'] = Items::getPossibleEnumValues('status');
        return view('_back.packs.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['yesno_lov'] = Items::getPossibleEnumValues('is_has_parking');
        $this->data['status_lov'] = Items::getPossibleEnumValues('status');
        $this->data['numbers_lov'] = self::_get_numbers();
        return view('_back.packs.crud', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $query = parent::_store($request->all());

        if(!($query instanceof Items)){
            return $query;
        }

        return redirect()->route('back.packs.show', array('item' => $query->id))
            ->with('message_success', 'Cambios guardados correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function show(Items $pack)
    {
        $this->data['status_lov'] = Items::getPossibleEnumValues('status');
        $this->data['yesno_lov'] = Items::getPossibleEnumValues('is_has_parking');
        $this->data['numbers_lov'] = self::_get_numbers();
        $this->data['query'] = parent::_show($pack);
        return view('_back.packs.crud', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Items $pack)
    {
        $query = parent::_update($request->all(), $pack);

        if(!($query instanceof Items)){
            return $query;
        }

        return redirect()->route('back.packs.show', array('pack' => $query->id))
            ->with('message_success', 'Cambios guardados correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function destroy(Items $pack)
    {
        parent::_destroy($pack);
        return redirect()
            ->route('back.packs.index')
            ->with('message_success', 'Cambios guardados correctamente');
    }

    public function additems(Request $request, Items $items_id){
        if ($request->isMethod('post')){
            parent::_insert_related_items($request->all(), $items_id->id);
            return redirect()
                ->route('back.plans.additems', ['items_id' => $items_id->id])
                ->with('message_success', 'Cambios guardados correctamente');
        }

        $items_selected = ItemsPacks::where('items_id', '=', $items_id->id)
            ->pluck('items_id_related')->all();
        $this->data['items'] = Items::where('status', '=', 'active')
                ->where('type', '=', 'plan')
                ->whereNotIn('id', $items_selected)
                ->orderBy('order', 'asc')->get();
        $this->data['items_selected'] = Items::where('status', '=', 'active')
                ->where('type', '=', 'plan')
                ->whereIn('id', $items_selected)
                ->orderBy('order', 'asc')->get();
        $this->data['query'] = $items_id;
        return view('_back.packs.crud_additems', $this->data);
    }

    public function translate(Request $request, Items $item){
        //preparamos el array de idiomas
        $array = array();
        foreach(config('translatable.locales') as $keylocale => $locale){
            $itemLang = $item->getTranslation('name', $keylocale);

            $array['name'] = $itemLang->name;
            $array['locale'][$keylocale] = $keylocale;
            $array['slug'][$keylocale] = '';
            $array['description'][$keylocale] = $itemLang->locale == $keylocale ? $itemLang->description : '';
            $array['seo_description'][$keylocale] = $itemLang->locale == $keylocale ? $itemLang->seo_description : '';
            $array['seo_keywords'][$keylocale] = $itemLang->locale == $keylocale ? $itemLang->seo_keywords : '';
        }

        parent::_insert_langs($array, $item);
        $this->data['query'] = parent::_show($item);
        return view('_back.packs.crud_langs', $this->data);
    }

    private function _get_numbers(){
        $array = array();
        $array[''] = 'Sin información';
        $array['0'] = 'El mismo día';
        for($x = 1; $x < 11; $x ++){
            $array[$x] = $x;
        }

        return $array;
    }
}

resources/views/_back/packs/crud.blade.php
@inject('helpers', 'App\Http\Controllers\AuxController')
@extends('_layouts/inicio')

@section ('body')

<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        @if(isset($query))
            <h1 class="pull-left">Pack: {{$query->name}}</h1>
        @else
            <h1 class="pull-left">Nuevo pack</h1>
        @endif
    </div><!--/container-->
</div><!--/breadcrumbs-->
<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('back.packs.index') }}" class="btn-u" role="button">
                Volver a la lista
            </a>
            <a href="{{ route('back.packs.create') }}" class="btn-u" role="button">
                Crear otro pack
            </a>
            @if(isset($query))
                <a href="{{ route('back.plans.additems', ['items_id' => $query->id]) }}" 
                   class="btn-u btn-u-green" role="button">
                    Empaquetar
                </a>
            @endif
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            <form class="margin-bottom-20" id="form_item" role="form" method="post" enctype="multipart/form-data" 
                action="{{ isset($query) ? route('back.packs.update', ['event' => $query->id]) : route('back.packs.store') }}">
                @if(isset($query))
                    @method('PUT')
                @endif
                @csrf
                <div class="row">
                    <div class="col-md-12">
                        @include('_layouts.messages', array('errors' => $errors))
                        @include('_back.packs.crud_info', array('query' => isset($query) ? $query : null))
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-9" id="div_crud_langs">
                        @include('_back.packs.crud_langs', array('query' => isset($query) ? $query : null))
                    </div>
                    <div class="col-md-3">
                        <div class="panel panel-default">
                            <div class="panel-heading">Acciones</div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn-u btn-block margin-bottom-25">
                                            Guardar
                                        </button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Status</label>
                                            {!! Form::select('status', $status_lov, 
                                                old('status', isset($query) ? $query->status: ''), 
                                                array('class' => 'form-control', 'id' => 'status')) !!}
                                        </div>
                                    </div>
                                </div>
                                <div id="div_crud_photos"> 
                                    @include('_back.packs.crud_photos', array('query' => isset($query) ? $query : null))
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section ('assets_end')
    <script src="{{ asset('assets/plugins/redactor/redactor.min.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('assets/plugins/redactor/redactor.css') }}">
    <script src="{{ asset('assets/plugins/redactor/lang/es.js') }}"></script>
    <script src="{{ asset('assets/plugins/redactor/plugins/read-more-plugin.js') }}"></script>

    <script src="{{ asset('assets/plugins/fancybox/source/jquery.fancybox.pack.js?v=2.1.5') }}"></script>
    <link rel="stylesheet" href="{{ asset('assets/plugins/fancybox/source/jquery.fancybox.css') }}">

    <link rel="stylesheet" href="{{ asset('assets/plugins/jquery-upload-file/uploadfile.css') }}">
    <script src="{{ asset('assets/plugins/jquery-upload-file/jquery.uploadfile.min.js') }}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            @if(isset($query))
                $('#btn_translate').on('click', function(event) {
                    $.get(ARNY.baseUrl + '/back/packs/translate/{{ $query->id }}',
                        function(data){
                            $('#div_crud_langs').html(data);
                            if($('.redactor').length){
                                $('.redactor').redactor({
                                    minHeight: 400,
                                    lang: 'es',
                                    plugins: ['leermas']
                                });
                            }
                        }
                    );
                    event.preventDefault();
                });
            @endif
            $("#fileuploader").uploadFile({
                url:"{{ route('back.packs.photos.store') }}",
                fileName:"p_file",
                onSuccess:function(files,data,xhr,pd){
                    $('#form_item').append('<input type="hidden" name="p_foto[]" value="'+data+'" />');
                }
            });
            if($('.redactor').length){
                $('.redactor').redactor({
                    minHeight: 400,
                    lang: 'es',
                    plugins: ['leermas']
                });
            }
        });
    </script>

    <script type="text/javascript">
        $(function(){
            if($(".fancybox").length){
                jQuery(".fancybox").fancybox({
                    groupAttr: 'data-rel',
                    prevEffect: 'fade',
                    nextEffect: 'fade',
                    openEffect  : 'elastic',
                    closeEffect  : 'fade',
                    closeBtn: true,
                    helpers: {
                        title: {
                            type: 'float'
                        }
                    }
                });
            }
        });
    </script>
    <style type="text/css">
        .btn-u-sm, a.btn-u-sm {
            padding: 5px 12px;
        }
    </style>
@stop

resources/views/_back/packs/crud_info.blade.php
<div class="panel panel-default">
    <div class="panel-heading">Datos</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Nombre</label>
                    <input type="text" class="form-control {{ $errors->has('name') ? 'border-rojo' : "" }}" 
                        name="{{ isset($query) ? '' : 'name' }}" {{ isset($query) ? 'disabled' : '' }} placeholder="Nombre"
                        value="{{ old('name.' . config('app.locale'), isset($query) ? $query->name : '') }}"/>
                    @if(isset($query))
                        <div class="note">
                            <strong>Nota:</strong>
                            Después podrás modificar y traducir el nombre del producto en la sección de textos 
                        </div>
                    @endif
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label>Precio p.p</label>
                    <input type="text" class="form-control {{ $errors->has('price') ? 'border-rojo' : "" }}" 
                        name="price" placeholder="Precio por persona"
                        value="{{ old('price', isset($query) ? $query->price: '') }}"/>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label>Precio p.p. rebajado</label>
                    <input type="text" class="form-control {{ $errors->has('new_price') ? 'border-rojo' : "" }}" 
                        name="new_price" placeholder="Precio rebajado"
                        value="{{ old('new_price', isset($query) ? $query->new_price: '') }}"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    <label>Duración (H:M h)</label>
                    <input type="text" class="form-control {{ $errors->has('duration') ? 'border-rojo' : "" }}" 
                        name="duration" placeholder="Duración"
                        value="{{ old('duration', isset($query) ? $query->duration: '') }}"/>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label>Mínimo personas</label>
                    <input type="text" class="form-control {{ $errors->has('min_pax') ? 'border-rojo' : "" }}" 
                        name="min_pax" placeholder="Mínimo personas"
                        value="{{ old('min_pax', isset($query) ? $query->min_pax: '') }}"/>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label>Máximo personas</label>
                    <input type="text" class="form-control {{ $errors->has('max_pax') ? 'border-rojo' : "" }}" 
                        name="max_pax" placeholder="Máximo personas"
                        value="{{ old('max_pax', isset($query) ? $query->max_pax: '') }}"/>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>Días de antelación para pedido</label>
                    {!! Form::select('advance_days', $numbers_lov, 
                        old('advance_days', isset($query) ? $query->advance_days: ''), 
                        array('class' => 'form-control', 'id' => 'advance_days')) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>Días de antelación para cancelar</label>
                    {!! Form::select('cancellation_days', $numbers_lov, 
                        old('cancellation_days', isset($query) ? $query->cancellation_days: ''), 
                        array('class' => 'form-control', 'id' => 'cancellation_days')) !!}
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/_back/packs/index.blade.php
@extends('_layouts/inicio')

@section ('body')

<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Packs</h1>
    </div>
</div>
<div class="container content profile">
    <div class="row">
        <div class="col-md-12">
            <a href="{{route('back.packs.create')}}" class="btn-u" role="button">
                Nuevo pack regalo
            </a>
        </div>     
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Búsqueda</div>
                <div class="panel-body">
                    <form role="form" method="get" enctype="multipart/form-data" action="{{ route('back.packs.index') }}">
                        <div class="row">
                            <div class="col-md-3">
                                <label>Categoría</label>
                                {!! Form::select('cat', array('' => 'Todos') + $labels_lov, 
                                    '', 
                                    array('class' => 'form-control', 'id' => 'labels_id')) !!}
                            </div>
                            @if(\Auth::user()->isAdmin())
                                <div class="col-md-3">
                                    <label>Proveedor</label>
                                    {!! Form::select('prov', array('' => 'Todos') + $users_lov, 
                                        '', 
                                        array('class' => 'form-control', 'id' => 'users_lov')) !!}
                                </div>
                            @endif
                            <div class="col-md-3">
                                <label>Status</label>
                                {!! Form::select('status', array('' => 'Todos') + $status_lov, 
                                    '', 
                                    array('class' => 'form-control', 'id' => 'status')) !!}
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn-u margin-top-25">
                                    Buscar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Items</div>
                <div class="panel-body">
                    @include('_layouts.messages', array('errors' => $errors))
                    <table class="table" id="tabla">
                        <thead>
                            <th>Nombre</th>
                            <th>Categoría</th>
                            <th>Proveedor</th>
                            <th>Precio</th>
                            <th>Status</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            @foreach($query as $item)
                                <tr>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->labels_id != null ? $item->label->name : '' }}</td>
                                    <td>{{ $item->user->name }}</td>
                                    <td>{{ $item->trueprice }}</td>
                                    <td>{{ $item->status }}</td>
                                    <td>
                                        <a href="{{ route('back.packs.show', array('id' => $item->id)) }}" 
                                           class="btn btn-primary btn-sm pull-left" role="button">
                                            <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                        <form action="{{ route('back.packs.destroy', [$item->id]) }}" method="POST" 
                                            onsubmit="if(!confirm('¿Estás seguro de querer borrar la actividad?')) return false"
                                            class="col-md-4">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger btn-sm" type="submit">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>     
    </div>
</div><!--/container-->    
<!--=== End Profile ===-->

@stop

@section ('assets_end')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/datatables.min.css') }}">
    <script src="{{ asset('assets/plugins/datatables/datatables.min.js') }}"></script>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla').DataTable({
                "language": {
                    "url": ARNY.baseUrl + "/assets/plugins/datatables/spanish.lang"
                },
                stateSave: true
            });
        });
    </script>
@stop