routes/web.php
	array('as' => 'wines', 'uses' => 'IndexController@redirect_wines'));*/

Route::group(array('middleware' => 'minificar', 'prefix' => LaravelLocalization::setLocale()), function(){
//Route::group(array('prefix' => LaravelLocalization::setLocale()), function(){
	Route::get('/', array('as' => '/', 'uses' => 'IndexController@index'));
	Route::get('politicas_cookies', array('as' => 'politicas_cookies', 'uses' => 'IndexController@politicas_cookies'));
	Route::get('politicas_privacidad', array('as' => 'politicas_privacidad', 'uses' => 'IndexController@politicas_privacidad'));

	Route::get(LaravelLocalization::transRoute('route.route_index'), 
		array('as' => 'routes.index', 'uses' => 'Routes\RoutesWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.route_show'), 
		array('as' => 'routes.show', 'uses' => 'Routes\RoutesWebController@show'));

	Route::get(LaravelLocalization::transRoute('route.search'), 
		array('as' => 'search', 'uses' => 'Plans\PlansWebController@search'));

	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-index'), 
		array('as' => 'enotourism-mallorca.events.index', 'uses' => 'Events\EventsWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-map'), 
		array('as' => 'enotourism-mallorca.events.map', 'uses' => 'Events\EventsWebController@map'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-create'), 
		array('as' => 'enotourism-mallorca.events.create', 'uses' => 'Events\EventsWebController@create'));
	Route::post(LaravelLocalization::transRoute('route.enotourism-mallorca-store'), 
		array('as' => 'enotourism-mallorca.events.store', 'uses' => 'Events\EventsWebController@store'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-show_event'), 
		array('as' => 'enotourism-mallorca.events.show', 'uses' => 'Events\EventsWebController@show'));


	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-gift'), 
		array('as' => 'enotourism-mallorca.gift', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-dis'), 
		array('as' => 'enotourism-mallorca.dis', 'uses' => 'Plans\PlansWebController@index_dis'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-user'), 
		array('as' => 'enotourism-mallorca.user', 'uses' => 'Users\UsersWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-item'), 
		array('as' => 'enotourism-mallorca.item', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-cat'), 
		array('as' => 'enotourism-mallorca.cat', 'uses' => 'Plans\PlansWebController@index_cat'));

	Route::any('orders/confirm_visit/{order_encrypted}/{set?}', array('as' => 'orders.confirm_visit', 
		'uses' => 'Orders\OrdersWebController@confirm_visit'));
	Route::any('orders/confirm_payment/{crypt}/{set?}', array('as' => 'orders.confirm_payment', 
		'uses' => 'Orders\OrdersWebController@confirm_payment'));
	Route::post('plans/stocks/get_time', array('as' => 'plans.stocks.get_time', 'uses' => 'PlansStocks\PlansStocksWebController@get_time'));
	Route::post('orders/get_time', array('as' => 'orders.get_time', 
		'uses' => 'Orders\OrdersPanelController@get_time'));
	Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
		['only' => ['store', 'update', 'destroy'], 'as' => 'events']);

	Route::any('plans/comment', array('as' => 'plans.comment', 'uses' => 'Plans\PlansWebController@comment'));

	Route::any('cart', array('as' => 'orders.index', 'uses' => 'Orders\OrdersWebController@index'));
	Route::post('cart/update', array('as' => 'orders.update', 'uses' => 'Orders\OrdersWebController@update'));
	Route::get('add_to_cart', array('as' => 'orders.add_to_cart', 'uses' => 'Orders\OrdersWebController@add_to_cart'));
	Route::get('orders/{code}/{email}', array('as' => 'orders.show', 'uses' => 'Orders\OrdersWebController@show'));
	Route::post('cart/save', array('as' => 'orders.save', 'uses' => 'Orders\OrdersWebController@save'));
	Route::get('cart/delete/{id}', array('as' => 'orders.delete', 'uses' => 'Orders\OrdersWebController@delete'));
	Route::get('cart/coupon/{coupons_id?}', array('as' => 'orders.coupon', 'uses' => 'Orders\OrdersWebController@coupon'));
	Route::get('cart/callback/{id}', array('as' => 'orders.callback', 'uses' => 'Orders\OrdersWebController@callback'));

	Route::get('temp_image_png', array('as' => 'index.temp_image_png', 'uses' => 'IndexController@temp_image_png'));

});

Auth::routes();
Imgfly::routes();

Route::get('back/orders/download_voucher/{orders_id}/{email}', 
	array('as' => 'back.orders.download_voucher', 'uses' => 'Orders\OrdersPanelController@download_voucher'));


Route::group(array('middleware' => 'auth'), function(){

	Route::get('back', 'HomeController@index')->name('back');

	Route::group(array('prefix' => 'back'), function(){

		Route::group(array('middleware' => 'admin'), function(){

			Route::resource('labels/langs', 'LabelsLangs\LabelsLangsController', 
				['only' => ['update'], 'as' => 'back.labels']);

			Route::resource('labels', 'Labels\LabelsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		});

		Route::group(array('middleware' => 'notuser'), function(){

			Route::resource('plans/stocks', 'PlansStocks\PlansStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);
			Route::get('plans/stocks/{items_id}', 
				array('as' => 'back.plans.stocks.show', 'uses' => 'PlansStocks\PlansStocksPanelController@show'));
				
			Route::resource('plans/photos', 'PlansPhotos\PlansPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);

			Route::resource('plans', 'Plans\PlansPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
            Route::get('plans/action/promoted/{item}', 
                array('as' => 'back.plans.promoted.toggle', 'uses' => 'Plans\PlansPanelController@toggle_promoted'));

			Route::resource('events/stocks', 'EventsStocks\EventsStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/stocks/{items_id}', 
				array('as' => 'back.events.stocks.show', 'uses' => 'EventsStocks\EventsStocksPanelController@show'));

			Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/photos/destroy/{photo}', 
				array('as' => 'back.events.photos.destroy', 'uses' => 'EventsPhotos\EventsPhotosPanelController@destroy'));

			Route::get('events/instagram/get/{item}', array('as' => 'back.events.instagram.get', 'uses' => 'Events\EventsPanelController@instagram_get'));
			Route::get('events/translate/{item}', array('as' => 'back.events.translate', 'uses' => 'Events\EventsPanelController@translate'));

			Route::resource('events', 'Events\EventsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::resource('packs/photos', 'PacksPhotos\PacksPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.packs']);
			Route::get('packs/photos/destroy/{photo}', 
				array('as' => 'back.packs.photos.destroy', 'uses' => 'PacksPhotos\PacksPhotosPanelController@destroy'));

			Route::any('packs/additems/{items_id}', 
				array('as' => 'back.plans.additems', 'uses' => 'Packs\PacksPanelController@additems'));

			Route::get('packs/translate/{item}', array('as' => 'back.packs.translate', 'uses' => 'Packs\PacksPanelController@translate'));
			Route::resource('packs', 'Packs\PacksPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::get('blogs/translate/{blog}', array('as' => 'back.blogs.translate', 'uses' => 'Routes\RoutesPanelController@translate'));
			Route::resource('blogs/photos', 'BlogsPhotos\BlogsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.blogs']);
			Route::get('blogs/photos/destroy/{photo}', 
				array('as' => 'back.blogs.photos.destroy', 'uses' => 'BlogsPhotos\BlogsPhotosPanelController@destroy'));
			Route::resource('routes', 'Routes\RoutesPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

			Route::get('users/action/promoted/{item}', 
				array('as' => 'back.users.promoted.toggle', 'uses' => 'Users\UsersPanelController@toggle_promoted'));

		});


		Route::resource('coupons', 'Coupons\CouponsPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		Route::resource('users/photos', 'UsersPhotos\UsersPhotosPanelController', 
			['only' => ['store', 'update', 'destroy'], 'as' => 'back.users']);

		Route::resource('users', 'Users\UsersPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


		Route::resource('orders', 'Orders\OrdersPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
		Route::get('back/orders/mark_booking/{order}/{action}', 
			array('as' => 'back.orders.mark_booking', 'uses' => 'Orders\OrdersPanelController@mark_booking'));
		/*Route::post('locations/get_districts', array('as' => 'back.locations.get_districts', 'uses' => 'Locations\LocationsPanelController@get_districts'));*/

	});
	
});


Route::get('sitemap', array('as' => 'sitemap', 'uses' => 'SitemapController@index'));
Route::get('/sitemap-plans.xml', array('as' => 'sitemap-plans', 'uses' => 'SitemapController@plans'));
Route::get('/sitemap-users.xml', array('as' => 'sitemap-users', 'uses' => 'SitemapController@users'));

app/Coupons.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Helpers;

class Coupons extends Model
{

	use Helpers;

    public function orders(){
        return $this->hasMany('\App\Orders', 'coupons_id')->orderBy('id', 'asc');
    }
}

app/Http/Controllers/Coupons/CouponsController.php
<?php

namespace App\Http\Controllers\Coupons;

use App\Coupons;
use Illuminate\Http\Request;
use App\Traits\Helpers;
use Intervention\Image\ImageManagerStatic as Image;

class CouponsController extends \App\Http\Controllers\Controller
{
    use Helpers;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function _index()
    {
        return Coupons::all();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected function _all()
    {
        return Coupons::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function _store($request)
    {
        $tmp = new Coupons;
        $tmp->code = mb_strtoupper($request['code'], 'UTF-8');
        $tmp->description = $request['description'];
		$tmp->active = $request['active'];
		$tmp->discount = $request['discount'];
        $tmp->save();

        return $tmp;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function _show(Coupons $coupon)
    {
        return $coupon;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function _update($request, Coupons $tmp)
    {
        $tmp->code = mb_strtoupper($request['code'], 'UTF-8');
        $tmp->description = $request['description'];
		$tmp->active = $request['active'];
		$tmp->discount = $request['discount'];
		$tmp->save();
        
        return $tmp;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function _destroy(Coupons $coupon)
    {
        $coupon->delete();

        return true;
    }
}

app/Http/Controllers/Coupons/CouponsPanelController.php
<?php

namespace App\Http\Controllers\Coupons;

use App\Coupons;
use Illuminate\Http\Request;

class CouponsPanelController extends CouponsController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['query'] = parent::_index();
        return view('_back.coupons.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['active_lov'] = Coupons::getPossibleEnumValues('active');
        return view('_back.coupons.crud', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->data['query'] = parent::_store($request->all());

        if($this->data['query'] == null){
            return redirect()->back()->with('message_error', 'Debes informar el nombre');
        }

        return redirect()
            ->route('back.coupons.show', array('coupon' => $this->data['query']->id))
            ->with('message_success', 'Cambios guardados correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function show(Coupons $coupon)
    {
        $this->data['active_lov'] = Coupons::getPossibleEnumValues('active');
        $this->data['query'] = parent::_show($coupon);
        return view('_back.coupons.crud', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Coupons $coupon)
    {
        $this->data['query'] = parent::_update($request->all(), $coupon);

        if($this->data['query'] == null){
            return redirect()->back()->with('message_error', 'Debes informar el nombre y subir una foto');
        }

        return redirect()
            ->route('back.coupons.show', array('coupon' => $this->data['query']->id))
            ->with('message_success', 'Cambios guardados correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function destroy(Coupons $coupon)
    {
        parent::_destroy($coupon);
        return redirect()
            ->route('back.coupons.index')
            ->with('message_success', 'Cambios guardados correctamente');
    }
}

app/Http/Controllers/Coupons/CouponsWebController.php
<?php

namespace App\Http\Controllers\Coupons;

use App\Bikes;
use Illuminate\Http\Request;

class CouponsWebController extends CouponsController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function show(Bikes $bikes)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function edit(Bikes $bikes)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bikes $bikes)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bikes $bikes)
    {
        //
    }
}

resources/views/_back/coupons/crud.blade.php
@extends('_layouts/inicio')

@section ('body')

<div class="breadcrumbs">
    <div class="container">
        @if(isset($query))
            <h1 class="pull-left">Cupón: {{ $query->name }}</h1>
        @else
            <h1 class="pull-left">Nuevo cupón</h1>
        @endif
    </div>
</div>
<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('back.coupons.index') }}" 
               class="btn-u btn-u-sea-shop btn-u-lg" role="button">
                Volver a la lista
            </a>
            <a href="{{ route('back.coupons.create') }}" 
               class="btn-u btn-u-sea-shop btn-u-lg" role="button">
                Crear otro cupón
            </a>
        </div>     
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            @include('_layouts.messages', array('errors' => $errors))
            <div class="panel panel-u margin-bottom-40 bg-grey">
                <div class="panel-body">
                    <form class="margin-bottom-20" role="form" method="post" enctype="multipart/form-data" 
                          action="{{ isset($query) ? route('back.coupons.update', $query->id) : route('back.coupons.store') }}">
                        @if(isset($query))
                            @method('PUT')
                        @endif
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Código</label>
                                    <input type="text" class="form-control" name="code" placeholder="Código" 
                                        value="{{ old('code', isset($query) ? $query->code : '') }}"/>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" name="description" placeholder="Descripción" 
                                        value="{{ old('description', isset($query) ? $query->description : '') }}"/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Activo</label>
                                    {!! Form::select('active', $active_lov, 
                                        old('active', isset($query) ? $query->active: ''), 
                                        array('class' => 'form-control', 'id' => 'active')) !!}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Descuento</label>
                                    <input type="text" class="form-control" name="discount" placeholder="Descuento" 
                                        value="{{ old('discount', isset($query) ? $query->discount : '') }}"/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <button type="submit" class="btn-u btn-u-sea-shop btn-block" style="margin-top: 25px">Guardar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section ('assets_end')

@stop

resources/views/_back/coupons/crud_langs.blade.php
<h2>Traducciones</h2>
<div class="row">
    <div class="col-md-12">
        <form class="margin-bottom-20" role="form" method="post"
            action="{{ route('back.labels.langs.update', [$query->id]) }}">
            @method('PUT')
            @csrf
            <div class="row">
                <div class="col-md-6 margin-top-15 col-md-offset-3">
                    <button type="submit" class="btn-u btn-u-sea-shop btn-block">Guardar traducciones</button>
                </div>
            </div>
            <div class="tab-v2 margin-top-40">
                <ul class="nav nav-tabs">
                    @foreach($query->langs as $lang)
                        <li class="{{ Request::get('tab') == 'langs' && Request::get('idioma') == $lang->locale ? 'active' : (!Request::has('idioma') && $loop->first ? 'active' : '')}}">
                            <a href="#{{ $lang->locale }}" data-toggle="tab">{{ config('translatable.locales')[$lang->locale] }}</a>
                        </li>
                    @endforeach
                </ul>
                <div class="tab-content bg-color-white">
                    @foreach($query->langs as $lang)
                        <div class="tab-pane fade in {{ Request::get('tab') == 'langs' && Request::get('idioma') == $lang->locale ? 'active' : (!Request::has('idioma') && $loop->first ? 'active' : '') }}"
                            id="{{ $lang->locale }}">
                            <input type="hidden" name="id[{{ $lang->locale }}]" value="{{ $lang->id }}"/>
                            <input type="hidden" name="locale[{{ $lang->locale }}]" value="{{ $lang->locale }}"/>
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" name="name[{{ $lang->locale }}]" class="form-control" 
                                            value="{{ old('name.' . $lang->locale, $lang->name) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Title</label>
                                        <input type="text" name="title[{{ $lang->locale }}]" class="form-control" 
                                            value="{{ old('title.' . $lang->locale, $lang->title) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Descripción</label>
                                        <textarea class="redactor" 
                                            name="description[{{ $lang->locale }}]">{{ old('description.' . $lang->locale, $lang->description) }}</textarea>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Seo tags</label>
                                                <textarea class="form-control" name="seo_keywords[{{ $lang->locale }}]" 
                                                    rows="5">{{ old('seo_keywords.'.$lang->locale, $lang->seo_keywords) }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Seo descripción</label>
                                                <textarea class="form-control" name="seo_description[{{ $lang->locale }}]" 
                                                    rows="8">{{ old('seo_description.'.$lang->locale, $lang->seo_description) }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 margin-top-15 col-md-offset-3">
                    <button type="submit" class="btn-u btn-u-sea-shop btn-block">Guardar traducciones</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/_back/coupons/index.blade.php
@extends('_layouts/inicio')

@section ('body')

<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Cupones</h1>
    </div>
</div>
<div class="container content profile">
    <div class="row">
        <div class="col-md-12">
            <a href="{{route('back.coupons.create')}}" 
               class="btn btn-u btn-u-lg" role="button">
                Crear cupón
            </a>
        </div>     
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            <table class="table" id="tabla">
                <thead>
                    <th>#</th>
                    <th>Código</th>
                    <th>Descripción</th>
                    <th>Activo</th>
                    <th>Descuento</th>
                    <th>Acciones</th>
                </thead>
                <tbody>
                    @foreach($query as $row)
                        <tr>
                            <td>{{ $row->id }}</td>
                            <td>{{ $row->code }}</td>
                            <td>{{ $row->description }}</td>
                            <td>{{ $row->active }}</td>
                            <td>{{ $row->discount }}</td>
                            <td>
                                <a href="{{ route('back.coupons.show', array('id' => $row->id)) }}" 
                                   class="btn btn-primary btn-sm pull-left" role="button">
                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                </a>
                                <form action="{{ route('back.coupons.destroy', [$row->id]) }}" method="POST" 
                                    onsubmit="if(!confirm('¿Estás seguro de querer borrar la categoría?')) return false"
                                    class="col-md-4">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-danger btn-sm" type="submit">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@stop

@section ('assets_end')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/datatables.min.css') }}">
    <script src="{{ asset('assets/plugins/datatables/datatables.min.js') }}"></script>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla').DataTable({
                "language": {
                    "url": ARNY.baseUrl + "/assets/plugins/datatables/spanish.lang"
                },
                stateSave: true
            });
        });
    </script>

@stop