routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test_mail', function () {
    //$order = App\Orders::find(51);
    //return new App\Mail\Voucher($order);
	//Mail::send(new App\Mail\Voucher($order));
    //return null;

    $params = array();
    $params['order'] = App\Orders::find(51);
	//return view('emails.pdf.pdf_voucher', $params);
    $pdf = \PDF::loadView('emails.pdf.pdf_voucher', $params);
    return $pdf->download('test.pdf');

});

Route::get('cron/reorder', array('as' => 'cron.reorder', 'uses' => 'CronController@reorder'));
Route::get('cron/send_emails', array('as' => 'cron.send_emails', 'uses' => 'CronController@send_emails'));
Route::any('generate_image_events', array('as' => 'generate_image_events', 'uses' => 'IndexController@generate_image_events'));
Route::get('pep_action', array('as' => 'pep.action', 'uses' => 'IndexController@pep_action'));


// temporal hasta que Google deje de indexar los vinos
/*Route::get(LaravelLocalization::transRoute('route.wines'), 
	array('as' => 'wines', 'uses' => 'IndexController@redirect_wines'));*/

Route::group(array('middleware' => 'minificar', 'prefix' => LaravelLocalization::setLocale()), function(){
//Route::group(array('prefix' => LaravelLocalization::setLocale()), function(){
	Route::get('/', array('as' => '/', 'uses' => 'IndexController@index'));
	Route::get('politicas_cookies', array('as' => 'politicas_cookies', 'uses' => 'IndexController@politicas_cookies'));
	Route::get('politicas_privacidad', array('as' => 'politicas_privacidad', 'uses' => 'IndexController@politicas_privacidad'));

	Route::get(LaravelLocalization::transRoute('route.route_index'), 
		array('as' => 'routes.index', 'uses' => 'Routes\RoutesWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.route_show'), 
		array('as' => 'routes.show', 'uses' => 'Routes\RoutesWebController@show'));

	Route::get(LaravelLocalization::transRoute('route.search'), 
		array('as' => 'search', 'uses' => 'Plans\PlansWebController@search'));

	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-index'), 
		array('as' => 'enotourism-mallorca.events.index', 'uses' => 'Events\EventsWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-map'), 
		array('as' => 'enotourism-mallorca.events.map', 'uses' => 'Events\EventsWebController@map'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-create'), 
		array('as' => 'enotourism-mallorca.events.create', 'uses' => 'Events\EventsWebController@create'));
	Route::post(LaravelLocalization::transRoute('route.enotourism-mallorca-store'), 
		array('as' => 'enotourism-mallorca.events.store', 'uses' => 'Events\EventsWebController@store'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-show_event'), 
		array('as' => 'enotourism-mallorca.events.show', 'uses' => 'Events\EventsWebController@show'));


	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-gift'), 
		array('as' => 'enotourism-mallorca.gift', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-dis'), 
		array('as' => 'enotourism-mallorca.dis', 'uses' => 'Plans\PlansWebController@index_dis'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-user'), 
		array('as' => 'enotourism-mallorca.user', 'uses' => 'Users\UsersWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-item'), 
		array('as' => 'enotourism-mallorca.item', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-cat'), 
		array('as' => 'enotourism-mallorca.cat', 'uses' => 'Plans\PlansWebController@index_cat'));

	Route::any('orders/confirm_visit/{order_encrypted}/{set?}', array('as' => 'orders.confirm_visit', 
		'uses' => 'Orders\OrdersWebController@confirm_visit'));
	Route::any('orders/confirm_payment/{crypt}/{set?}', array('as' => 'orders.confirm_payment', 
		'uses' => 'Orders\OrdersWebController@confirm_payment'));
	Route::post('plans/stocks/get_time', array('as' => 'plans.stocks.get_time', 'uses' => 'PlansStocks\PlansStocksWebController@get_time'));
	Route::post('orders/get_time', array('as' => 'orders.get_time', 
		'uses' => 'Orders\OrdersPanelController@get_time'));
	Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
		['only' => ['store', 'update', 'destroy'], 'as' => 'events']);

	Route::any('plans/comment', array('as' => 'plans.comment', 'uses' => 'Plans\PlansWebController@comment'));

	Route::any('cart', array('as' => 'orders.index', 'uses' => 'Orders\OrdersWebController@index'));
	Route::post('cart/update', array('as' => 'orders.update', 'uses' => 'Orders\OrdersWebController@update'));
	Route::get('add_to_cart', array('as' => 'orders.add_to_cart', 'uses' => 'Orders\OrdersWebController@add_to_cart'));
	Route::get('orders/{code}/{email}', array('as' => 'orders.show', 'uses' => 'Orders\OrdersWebController@show'));
	Route::post('cart/save', array('as' => 'orders.save', 'uses' => 'Orders\OrdersWebController@save'));
	Route::get('cart/delete/{id}', array('as' => 'orders.delete', 'uses' => 'Orders\OrdersWebController@delete'));
	Route::get('cart/coupon/{coupons_id?}', array('as' => 'orders.coupon', 'uses' => 'Orders\OrdersWebController@coupon'));
	Route::get('cart/callback/{id}', array('as' => 'orders.callback', 'uses' => 'Orders\OrdersWebController@callback'));

	Route::get('temp_image_png', array('as' => 'index.temp_image_png', 'uses' => 'IndexController@temp_image_png'));

});

Auth::routes();
Imgfly::routes();

Route::get('back/orders/download_voucher/{orders_id}/{email}', 
	array('as' => 'back.orders.download_voucher', 'uses' => 'Orders\OrdersPanelController@download_voucher'));


Route::group(array('middleware' => 'auth'), function(){

	Route::get('back', 'HomeController@index')->name('back');

	Route::group(array('prefix' => 'back'), function(){

		Route::group(array('middleware' => 'admin'), function(){

			Route::resource('labels/langs', 'LabelsLangs\LabelsLangsController', 
				['only' => ['update'], 'as' => 'back.labels']);

			Route::resource('labels', 'Labels\LabelsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		});

		Route::group(array('middleware' => 'notuser'), function(){

			Route::resource('plans/stocks', 'PlansStocks\PlansStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);
			Route::get('plans/stocks/{items_id}', 
				array('as' => 'back.plans.stocks.show', 'uses' => 'PlansStocks\PlansStocksPanelController@show'));
				
			Route::resource('plans/photos', 'PlansPhotos\PlansPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);

			Route::resource('plans', 'Plans\PlansPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
            Route::get('plans/action/promoted/{item}', 
                array('as' => 'back.plans.promoted.toggle', 'uses' => 'Plans\PlansPanelController@toggle_promoted'));

			Route::resource('events/stocks', 'EventsStocks\EventsStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/stocks/{items_id}', 
				array('as' => 'back.events.stocks.show', 'uses' => 'EventsStocks\EventsStocksPanelController@show'));

			Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/photos/destroy/{photo}', 
				array('as' => 'back.events.photos.destroy', 'uses' => 'EventsPhotos\EventsPhotosPanelController@destroy'));

			Route::get('events/instagram/get/{item}', array('as' => 'back.events.instagram.get', 'uses' => 'Events\EventsPanelController@instagram_get'));
			Route::get('events/translate/{item}', array('as' => 'back.events.translate', 'uses' => 'Events\EventsPanelController@translate'));

			Route::resource('events', 'Events\EventsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::resource('packs/photos', 'PacksPhotos\PacksPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.packs']);
			Route::get('packs/photos/destroy/{photo}', 
				array('as' => 'back.packs.photos.destroy', 'uses' => 'PacksPhotos\PacksPhotosPanelController@destroy'));

			Route::any('packs/additems/{items_id}', 
				array('as' => 'back.plans.additems', 'uses' => 'Packs\PacksPanelController@additems'));

			Route::get('packs/translate/{item}', array('as' => 'back.packs.translate', 'uses' => 'Packs\PacksPanelController@translate'));
			Route::resource('packs', 'Packs\PacksPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::get('blogs/translate/{blog}', array('as' => 'back.blogs.translate', 'uses' => 'Routes\RoutesPanelController@translate'));
			Route::resource('blogs/photos', 'BlogsPhotos\BlogsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.blogs']);
			Route::get('blogs/photos/destroy/{photo}', 
				array('as' => 'back.blogs.photos.destroy', 'uses' => 'BlogsPhotos\BlogsPhotosPanelController@destroy'));
			Route::resource('routes', 'Routes\RoutesPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

			Route::get('users/action/promoted/{item}', 

resources/views/_layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    IbRentabike
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">Login</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/_layouts/footer.blade.php
<div class="footer-v4 {{ $agent->isMobile() ? 'margin-bottom-50' : '' }}">
    <!--div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 md-margin-bottom-40">
                    <a href="index.html"><img class="footer-logo" src="assets/img/logo-2.png" alt=""></a>
                    <p>About Unify dolor sit amet, consectetur adipiscing elit. Maecenas eget nisl id libero tincidunt sodales.</p>
                    <br>
                    <ul class="list-unstyled address-list margin-bottom-20">
                        <li><i class="fa fa-angle-right"></i>California, US, Lorem Lis Street, Orange, 25</li>
                        <li><i class="fa fa-angle-right"></i>Phone: 800 123 3456</li>
                        <li><i class="fa fa-angle-right"></i>Fax: 800 123 3456</li>
                        <li><i class="fa fa-angle-right"></i>Email: info@anybiz.co</li>
                    </ul>

                    <ul class="list-inline shop-social">
                        <li><a href="#"><i class="fb rounded-md fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="tw rounded-md fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="gp rounded-md fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="yt rounded-md fa fa-youtube"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-3">
                    <div class="row">
                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Secciones</h2>
                            <ul class="list-unstyled simple-list margin-bottom-20">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li><a href="#">Documentos </a></li>
                                <li><a href="#">Francisco papa</a></li>
                                <li>...</li>
                            </ul>
                        </div>

                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Temas</h2>
                            <ul class="list-unstyled simple-list">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li><a href="#">Documentos </a></li>
                                <li><a href="#">Francisco papa</a></li>
                                <li>...</li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-2 col-sm-3">
                    <div class="row">
                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Utilidades</h2>
                            <ul class="list-unstyled simple-list margin-bottom-20">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li><a href="#">Documentos </a></li>
                                <li>...</li>
                            </ul>
                        </div>

                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Documentos</h2>
                            <ul class="list-unstyled simple-list">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li><a href="#">Documentos </a></li>
                                <li><a href="#">Francisco papa</a></li>
                                <li>...</li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-2 col-sm-3">
                    <div class="row">
                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Publicidad</h2>
                            <ul class="list-unstyled simple-list margin-bottom-20">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li><a href="#">Documentos </a></li>
                                <li><a href="#">Francisco papa</a></li>
                                <li>...</li>
                            </ul>
                        </div>

                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Contacto</h2>
                            <ul class="list-unstyled simple-list">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li><a href="#">Documentos </a></li>
                                <li><a href="#">Francisco papa</a></li>
                                <li>...</li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-2 col-sm-3">
                    <div class="row">
                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Utilidades</h2>
                            <ul class="list-unstyled simple-list margin-bottom-20">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li>...</li>
                            </ul>
                        </div>

                        <div class="col-sm-12 col-xs-6">
                            <h2 class="thumb-headline">Documentos</h2>
                            <ul class="list-unstyled simple-list">
                                <li><a href="#">Ultima Hora</a></li>
                                <li><a href="#">Exclusiva</a></li>
                                <li>...</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div-->

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>
                        {!! date('Y') . " &copy; " . config('constants.NAMEWEB') . " ALL Rights Reserved" !!}
                    </p>
                </div>
                <div class="col-md-6">
                    <ul class="list-inline sponsors-icons pull-right">
                        <li><i class="fa fa-cc-stripe"></i></li>
                        <li><i class="fa fa-money"></i></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/_layouts/header.blade.php
<div class="header-v5 header-static">
    <!-- Topbar v3 -->
    <div class="topbar-v3">
        <div class="search-open">
            <div class="container">
                <input type="text" class="form-control" placeholder="Search">
                <div class="search-close"><i class="icon-close"></i></div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <!-- Topbar Navigation -->
                    <ul class="left-topbar">
                        <li>
                            <a>Idioma ({{ LaravelLocalization::getCurrentLocale() }})</a>
                            <ul class="language">
                                <li class="active">
                                    <a href="{{ url('/') }}">
                                        Español (ES)&nbsp;
                                        @if(LaravelLocalization::getCurrentLocale() == 'es')
                                            <i class="fa fa-check"></i>
                                        @endif
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ LaravelLocalization::getLocalizedURL('ca') }}">
                                        Català (CAT)&nbsp;
                                        @if(LaravelLocalization::getCurrentLocale() == 'ca')
                                            <i class="fa fa-check"></i>
                                        @endif
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ LaravelLocalization::getLocalizedURL('en') }}">
                                        English (EN)&nbsp;
                                        @if(LaravelLocalization::getCurrentLocale() == 'en')
                                            <i class="fa fa-check"></i>
                                        @endif
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul><!--/end left-topbar-->
                </div>
                <div class="col-sm-6">
                    <ul class="list-inline right-topbar pull-right">
                        @if(\Auth::check())
                            <li><a href="{{ route('back') }}">{{ trans('base.hola') . " " . \Auth::user()->name }}</a></li>
                        @else
                            <li><a href="{{ route('login') }}">{{ trans('inicio.login') }}</a> | <a href="{{ route('register') }}">{{ trans('inicio.registrarse') }}</a></li>
                        @endif
                        <li><i class="search fa fa-search search-button"></i></li>
                    </ul>
                </div>
            </div>
        </div><!--/container-->
    </div>

    @include('_layouts.nav')
</div>

resources/views/_layouts/menu.blade.php
<div class="collapse navbar-collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
        @if(isset($menu_routes) && $menu_routes->count() > 0)
            <li class="dropdown">
                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                    {{ trans('events.rutas_de_vino_mallorca') }}
                </a>
                <ul class="dropdown-menu">
                    <li class="padding-top-10 padding-bottom-15"><a href="{{ route('routes.index') }}" class="btn btn-u button margin-lr-15 color-blanco">{{ trans('blog.ver_todas_las_rutas') }}</a></li>
                    @foreach($menu_routes as $tmproute)
                        <li>
                            <a href="{{ route('routes.show', ['route' => $tmproute->slug]) }}">
                                {{ $tmproute->name }}
                            </a>
                        </li>
                    @endforeach
                </ul>
            </li>
        @endif
        <li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">
                {{ trans('inicio.enoturismo') }}
            </a>
            <ul class="dropdown-menu">
                <li class="padding-lr-15 padding-top-10"><strong>{{ trans('inicio.turismo_de_vino') }}</strong></li>
                <li><a href="{{ route('enotourism-mallorca.cat') }}"><i class="fa fa-glass"></i> {{ trans('inicio.enotourism-mallorca') }}</a></li>
                <li><a href="{{ route('enotourism-mallorca.events.index') }}"><i class="fa fa-calendar"></i> {{ trans('inicio.eventos_con_vino_en_mallorca') }}</a></li>
                <li><a href="{{ route('enotourism-mallorca.events.map') }}"><i class="fa fa-ellipsis-h"></i> {{ trans('events.rutas_de_vino_mallorca') }}</a></li>
                <hr class="margin-top-bottom-10" />
                <li class="padding-lr-15"><strong>{{ trans('plan.categorias') }}</strong></li>
                @foreach($menu_enoturismo_2 as $tmp)
                    <li><a href="{{ route($tmp->category . '.cat', ['cat' => $tmp->slug]) }}">{{ $tmp->name }}</a></li>
                @endforeach
            </ul>
        </li>
    </ul>
</div>

resources/views/_layouts/nav_panel.blade.php
<nav class="navbar navbar-default margin-bottom-0">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" 
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ route('back') }}" class="navbar-brand">{{ \Auth::user()->name }}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            @if(Auth::check() && Auth::user()->isAdmin())
             <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fire-extinguisher"></i> Admin
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('back.labels.index') }}">Categorias</a></li>
                        <li><a href="{{ route('back.users.index') }}">Usuarios/Empresas</a></li>
                        <li><a href="{{ route('back.coupons.index') }}">Cupones</a></li>
                    </ul>
                </li>
            </ul>
            @endif
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i> {{ trans('panel.perfil') }} 
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('back.users.show', [\Auth::id()]) }}">{{trans('panel.modificar_info')}}</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if(Auth::check() && Auth::user()->role != 'user')
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
                        aria-expanded="false">
                        <i class="fa fa-shopping-basket"></i> {{ trans('panel.items') }} 
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('back.plans.index') }}">{{trans('panel.listado_plans')}}</a></li>
                        <li><a href="{{ route('back.events.index') }}">{{trans('panel.listado_events')}}</a></li>
                        <li><a href="{{ route('back.routes.index') }}">{{trans('panel.listado_routes')}}</a></li>
                        <li><a href="{{ route('back.packs.index') }}">{{trans('panel.listado_packs')}}</a></li>
                    </ul>
                </li>
                @endif
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
                        aria-expanded="false">
                        <i class="fa fa-cc-visa"></i> {{ trans('panel.pedidos') }} 
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('back.orders.index') }}">{{trans('panel.listado_pedidos')}}</a></li>
                    </ul>
                </li>
                <li class="active">
                    <form id="logout-form" action="{{ route('logout') }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-link margin-top-8"><i class="fa fa-stop-circle"></i> Desconectar <span class="sr-only">(current)</span></button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>