routes/web.php
	array('as' => 'wines', 'uses' => 'IndexController@redirect_wines'));*/

Route::group(array('middleware' => 'minificar', 'prefix' => LaravelLocalization::setLocale()), function(){
//Route::group(array('prefix' => LaravelLocalization::setLocale()), function(){
	Route::get('/', array('as' => '/', 'uses' => 'IndexController@index'));
	Route::get('politicas_cookies', array('as' => 'politicas_cookies', 'uses' => 'IndexController@politicas_cookies'));
	Route::get('politicas_privacidad', array('as' => 'politicas_privacidad', 'uses' => 'IndexController@politicas_privacidad'));

	Route::get(LaravelLocalization::transRoute('route.route_index'), 
		array('as' => 'routes.index', 'uses' => 'Routes\RoutesWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.route_show'), 
		array('as' => 'routes.show', 'uses' => 'Routes\RoutesWebController@show'));

	Route::get(LaravelLocalization::transRoute('route.search'), 
		array('as' => 'search', 'uses' => 'Plans\PlansWebController@search'));

	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-index'), 
		array('as' => 'enotourism-mallorca.events.index', 'uses' => 'Events\EventsWebController@index'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-map'), 
		array('as' => 'enotourism-mallorca.events.map', 'uses' => 'Events\EventsWebController@map'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-create'), 
		array('as' => 'enotourism-mallorca.events.create', 'uses' => 'Events\EventsWebController@create'));
	Route::post(LaravelLocalization::transRoute('route.enotourism-mallorca-store'), 
		array('as' => 'enotourism-mallorca.events.store', 'uses' => 'Events\EventsWebController@store'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-show_event'), 
		array('as' => 'enotourism-mallorca.events.show', 'uses' => 'Events\EventsWebController@show'));


	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-gift'), 
		array('as' => 'enotourism-mallorca.gift', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-dis'), 
		array('as' => 'enotourism-mallorca.dis', 'uses' => 'Plans\PlansWebController@index_dis'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-user'), 
		array('as' => 'enotourism-mallorca.user', 'uses' => 'Users\UsersWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-item'), 
		array('as' => 'enotourism-mallorca.item', 'uses' => 'Plans\PlansWebController@show'));
	Route::get(LaravelLocalization::transRoute('route.enotourism-mallorca-cat'), 
		array('as' => 'enotourism-mallorca.cat', 'uses' => 'Plans\PlansWebController@index_cat'));

	Route::any('orders/confirm_visit/{order_encrypted}/{set?}', array('as' => 'orders.confirm_visit', 
		'uses' => 'Orders\OrdersWebController@confirm_visit'));
	Route::any('orders/confirm_payment/{crypt}/{set?}', array('as' => 'orders.confirm_payment', 
		'uses' => 'Orders\OrdersWebController@confirm_payment'));
	Route::post('plans/stocks/get_time', array('as' => 'plans.stocks.get_time', 'uses' => 'PlansStocks\PlansStocksWebController@get_time'));
	Route::post('orders/get_time', array('as' => 'orders.get_time', 
		'uses' => 'Orders\OrdersPanelController@get_time'));
	Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
		['only' => ['store', 'update', 'destroy'], 'as' => 'events']);

	Route::any('plans/comment', array('as' => 'plans.comment', 'uses' => 'Plans\PlansWebController@comment'));

	Route::any('cart', array('as' => 'orders.index', 'uses' => 'Orders\OrdersWebController@index'));
	Route::post('cart/update', array('as' => 'orders.update', 'uses' => 'Orders\OrdersWebController@update'));
	Route::get('add_to_cart', array('as' => 'orders.add_to_cart', 'uses' => 'Orders\OrdersWebController@add_to_cart'));
	Route::get('orders/{code}/{email}', array('as' => 'orders.show', 'uses' => 'Orders\OrdersWebController@show'));
	Route::post('cart/save', array('as' => 'orders.save', 'uses' => 'Orders\OrdersWebController@save'));
	Route::get('cart/delete/{id}', array('as' => 'orders.delete', 'uses' => 'Orders\OrdersWebController@delete'));
	Route::get('cart/coupon/{coupons_id?}', array('as' => 'orders.coupon', 'uses' => 'Orders\OrdersWebController@coupon'));
	Route::get('cart/callback/{id}', array('as' => 'orders.callback', 'uses' => 'Orders\OrdersWebController@callback'));

	Route::get('temp_image_png', array('as' => 'index.temp_image_png', 'uses' => 'IndexController@temp_image_png'));

});

Auth::routes();
Imgfly::routes();

Route::get('back/orders/download_voucher/{orders_id}/{email}', 
	array('as' => 'back.orders.download_voucher', 'uses' => 'Orders\OrdersPanelController@download_voucher'));


Route::group(array('middleware' => 'auth'), function(){

	Route::get('back', 'HomeController@index')->name('back');

	Route::group(array('prefix' => 'back'), function(){

		Route::group(array('middleware' => 'admin'), function(){

			Route::resource('labels/langs', 'LabelsLangs\LabelsLangsController', 
				['only' => ['update'], 'as' => 'back.labels']);

			Route::resource('labels', 'Labels\LabelsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		});

		Route::group(array('middleware' => 'notuser'), function(){

			Route::resource('plans/stocks', 'PlansStocks\PlansStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);
			Route::get('plans/stocks/{items_id}', 
				array('as' => 'back.plans.stocks.show', 'uses' => 'PlansStocks\PlansStocksPanelController@show'));
				
			Route::resource('plans/photos', 'PlansPhotos\PlansPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.plans']);

			Route::resource('plans', 'Plans\PlansPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
            Route::get('plans/action/promoted/{item}', 
                array('as' => 'back.plans.promoted.toggle', 'uses' => 'Plans\PlansPanelController@toggle_promoted'));

			Route::resource('events/stocks', 'EventsStocks\EventsStocksPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/stocks/{items_id}', 
				array('as' => 'back.events.stocks.show', 'uses' => 'EventsStocks\EventsStocksPanelController@show'));

			Route::resource('events/photos', 'EventsPhotos\EventsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.events']);
			Route::get('events/photos/destroy/{photo}', 
				array('as' => 'back.events.photos.destroy', 'uses' => 'EventsPhotos\EventsPhotosPanelController@destroy'));

			Route::get('events/instagram/get/{item}', array('as' => 'back.events.instagram.get', 'uses' => 'Events\EventsPanelController@instagram_get'));
			Route::get('events/translate/{item}', array('as' => 'back.events.translate', 'uses' => 'Events\EventsPanelController@translate'));

			Route::resource('events', 'Events\EventsPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::resource('packs/photos', 'PacksPhotos\PacksPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.packs']);
			Route::get('packs/photos/destroy/{photo}', 
				array('as' => 'back.packs.photos.destroy', 'uses' => 'PacksPhotos\PacksPhotosPanelController@destroy'));

			Route::any('packs/additems/{items_id}', 
				array('as' => 'back.plans.additems', 'uses' => 'Packs\PacksPanelController@additems'));

			Route::get('packs/translate/{item}', array('as' => 'back.packs.translate', 'uses' => 'Packs\PacksPanelController@translate'));
			Route::resource('packs', 'Packs\PacksPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


			Route::get('blogs/translate/{blog}', array('as' => 'back.blogs.translate', 'uses' => 'Routes\RoutesPanelController@translate'));
			Route::resource('blogs/photos', 'BlogsPhotos\BlogsPhotosPanelController', 
				['only' => ['store', 'update', 'destroy'], 'as' => 'back.blogs']);
			Route::get('blogs/photos/destroy/{photo}', 
				array('as' => 'back.blogs.photos.destroy', 'uses' => 'BlogsPhotos\BlogsPhotosPanelController@destroy'));
			Route::resource('routes', 'Routes\RoutesPanelController', 
				['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

			Route::get('users/action/promoted/{item}', 
				array('as' => 'back.users.promoted.toggle', 'uses' => 'Users\UsersPanelController@toggle_promoted'));

		});


		Route::resource('coupons', 'Coupons\CouponsPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);

		Route::resource('users/photos', 'UsersPhotos\UsersPhotosPanelController', 
			['only' => ['store', 'update', 'destroy'], 'as' => 'back.users']);

		Route::resource('users', 'Users\UsersPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);


		Route::resource('orders', 'Orders\OrdersPanelController', 
			['only' => ['index', 'create', 'store', 'show', 'update', 'destroy'], 'as' => 'back']);
		Route::get('back/orders/mark_booking/{order}/{action}', 
			array('as' => 'back.orders.mark_booking', 'uses' => 'Orders\OrdersPanelController@mark_booking'));
		/*Route::post('locations/get_districts', array('as' => 'back.locations.get_districts', 'uses' => 'Locations\LocationsPanelController@get_districts'));*/

	});
	
});


Route::get('sitemap', array('as' => 'sitemap', 'uses' => 'SitemapController@index'));
Route::get('/sitemap-plans.xml', array('as' => 'sitemap-plans', 'uses' => 'SitemapController@plans'));
Route::get('/sitemap-users.xml', array('as' => 'sitemap-users', 'uses' => 'SitemapController@users'));

app/Labels.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;
use App\Traits\Helpers;

class Labels extends Model
{
    use Helpers;
    use Translatable;
    public $translatedAttributes = ['name', 'title', 'slug', 'description', 'seo_description', 'seo_keywords'];

    public function langs(){
        return $this->hasMany('\App\LabelsLangs', 'labels_id')->orderBy('id', 'asc');
    }

    public function plans(){
        return $this->hasMany('\App\Items', 'labels_id')->where('type', '=', 'plan')->orderBy('order', 'asc');
    }

    public function labels(){
        return $this->hasMany('\App\Labels', 'labels_id')->orderBy('id', 'asc');
    }

    public function label(){
        return $this->belongsTo('\App\Labels', 'labels_id');
    }

    public function labels_by_cat(){
        return $this->hasMany('\App\Labels', 'category', 'category')->orderBy('id', 'asc');
    }

}

app/Http/Controllers/Labels/LabelsController.php
<?php

namespace App\Http\Controllers\Labels;

use App\Labels;
use App\LabelsLangs;
use Illuminate\Http\Request;
use App\Traits\Helpers;
use Intervention\Image\ImageManagerStatic as Image;

class LabelsController extends \App\Http\Controllers\Controller
{
    use Helpers;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function _index()
    {
        return Labels::whereNull('labels_id')->get();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected function _all()
    {
        return Labels::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function _store($request)
    {
        $tmp = new Labels;
        $tmp->labels_id = $request['labels_id'];
        $tmp->category = $request['category'];
        $tmp->status = $request['status'];
        $tmp->icon = isset($request['icon']) ? $request['icon'] : null;
        $tmp->save();

        if($request['p_foto'] != null){
            $tmp = self::__upload_image($request, $tmp);
        }
        if($request['p_menu'] != null){
            $tmp = self::__upload_image_small($request, $tmp);
        }

        foreach(config('translatable.locales') as $keylocale => $locale){
            $lang = new LabelsLangs;
            $lang->locale = $keylocale;
            $lang->labels_id = $tmp->id;
            $lang->save();
        }

        return $tmp;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function _show(Labels $location)
    {
        return $location;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function _update($request, Labels $tmp)
    {
        $tmp->labels_id = $request['labels_id'];
        $tmp->category = $request['category'];
        $tmp->status = $request['status'];
        $tmp->icon = isset($request['icon']) ? $request['icon'] : null;
        $tmp->save();

        if(isset($request['p_foto']) && $request['p_foto'] != null){
            logger('entro1');
            $tmp = self::__upload_image($request, $tmp);
        }
        if(isset($request['p_menu']) && $request['p_menu'] != null){
            logger('entro2');
            $tmp = self::__upload_image_small($request, $tmp);
        }

        return $tmp;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function _destroy(Labels $location)
    {
        $ruta = 'upload/labels/'.$location->id.'/';
        if(is_dir($ruta)){
            $success = \File::deleteDirectory($ruta, true);
            rmdir($ruta);
            if(!$success){
                throw new \Exception('El directorio de imagenes de '.$location->id.' no existe');
            }
        }

        $location->delete();

        return true;
    }

    private function __upload_image($request, $tmp){
        $ruta = 'upload/labels/'.$tmp->id.'/';
        \File::makeDirectory($ruta, 0775, true, true);

        // read image from temporary file
        $img = Image::make(base64_decode(substr($request['p_foto'], strpos($request['p_foto'], ",")+1)))->encode('webp', 90);

        $tmp->url = $ruta . $tmp->id . ".webp";
        $tmp->save();

        /*****************REDIMENSIONAMOS IMAGEN************************/
        $img->resize(1600, null, function ($constraint) {
            $constraint->aspectRatio();
        });
        $img->brightness(-10);
        $img->save($tmp->url);
        if(env("APP_ENV") != 'local'){
            $this->set_72dpi_image($tmp->url);
        }

        return $tmp;
    }

    private function __upload_image_small($request, $tmp){
        $ruta = 'upload/labels/'.$tmp->id.'/';
        \File::makeDirectory($ruta, 0775, true, true);

        // read image from temporary file
        $img = Image::make(base64_decode(substr($request['p_menu'], strpos($request['p_menu'], ",")+1)))->encode('webp', 90);

        $tmp->icon = $ruta . $tmp->category . "_" .  $tmp->id . ".webp";
        $tmp->save();

        /*****************REDIMENSIONAMOS IMAGEN************************/
        $img->resize(250, null, function ($constraint) {
            $constraint->aspectRatio();
        });
        $img->brightness(-20);
        $img->save($tmp->icon);
        if(env("APP_ENV") != 'local'){
            $this->set_72dpi_image($tmp->icon);
        }

        return $tmp;
    }
}

app/Http/Controllers/Labels/LabelsWebController.php
<?php

namespace App\Http\Controllers\BikesBrands;

use App\Bikes;
use Illuminate\Http\Request;

class BikesBrandsWebController extends BikesBrandsController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function show(Bikes $bikes)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function edit(Bikes $bikes)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bikes $bikes)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bikes  $bikes
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bikes $bikes)
    {
        //
    }
}

resources/views/_back/labels/crud.blade.php
@extends('_layouts/inicio')

@section ('body')

<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        @if(isset($query))
            <h1 class="pull-left">Categoría: {{ $query->name }}</h1>
        @else
            <h1 class="pull-left">Nueva categoría</h1>
        @endif
    </div><!--/container-->
</div><!--/breadcrumbs-->
<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('back.labels.index') }}" 
               class="btn-u btn-u-sea-shop btn-u-lg" role="button">
                Volver a la lista
            </a>
            <a href="{{ route('back.labels.create') }}" 
               class="btn-u btn-u-sea-shop btn-u-lg" role="button">
                Crear otra categoria
            </a>
        </div>     
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            @include('_layouts.messages', array('errors' => $errors))
            <div class="panel panel-u margin-bottom-40 bg-grey">
                <div class="panel-body">
                    <form class="margin-bottom-20" role="form" method="post" enctype="multipart/form-data" 
                          action="{{ isset($query) ? route('back.labels.update', $query->id) : route('back.labels.store') }}">
                        @if(isset($query))
                            @method('PUT')
                        @endif
                        @csrf
                        <div class="row">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Status</label>
                                    {!! Form::select('status', $status, 
                                        old('status', isset($query) ? $query->status : ''), 
                                        array('class' => 'form-control', 'id' => 'status')) !!}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Categoría padre</label>
                                    {!! Form::select('labels_id', array('' => '') + $labels, 
                                        old('labels_id', isset($query) ? $query->labels_id : ''), 
                                        array('class' => 'form-control', 'id' => 'labels_id')) !!}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Subir imagen de cabecera</label>
                                    <input id="p_foto" type="hidden" name="p_foto">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Subir imagen pequeña de menú</label>
                                    <input id="p_menu" type="hidden" name="p_menu">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Tipo</label>
                                    {!! Form::select('category', $categories, 
                                        old('category', isset($query) ? $query->category : ''), 
                                        array('class' => 'form-control', 'id' => 'category')) !!}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    @if(isset($query) && $query->url != null)
                                        <label>Imagen de cabecera</label>
                                        <a class="fancybox" data-rel="galeria_fotos"
                                            title="{{ $query->name }}"
                                            href="{{ url('/') . '/' . $query->url }}">
                                            <img src="{{ url('/') . '/' . $query->url }}" alt="{{ $query->name }}" class="img-responsive" />
                                        </a>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    @if(isset($query) && $query->icon != null)
                                        <label>Imagen de pequeña</label>
                                        <a class="fancybox" data-rel="galeria_fotos" title="{{ $query->name }}"
                                            href="{{ url('/') . '/' . $query->icon }}">
                                            <img src="{{ url('/') . '/' . $query->icon }}" alt="{{ $query->name }}" class="img-responsive" />
                                        </a>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <button type="submit" class="btn-u btn-u-sea-shop btn-block" style="margin-top: 25px">Guardar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-md-12">
                            @if(isset($query))
                                @include('_back.labels.crud_langs', array('query' => $query))
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section ('assets_end')
    <link rel="stylesheet" href="{{ asset('assets/plugins/crop-image/components/imgareaselect/css/imgareaselect-default.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/crop-image/css/jquery.awesome-cropper.css') }}">
    <script src="{{ asset('assets/plugins/crop-image/components/imgareaselect/scripts/jquery.imgareaselect.js') }}"></script>
    <script src="{{ asset('assets/plugins/crop-image/build/jquery.awesome-cropper.js') }}"></script>

    <link rel="stylesheet" href="{{ asset('assets/plugins/fancybox/source/jquery.fancybox.css') }}">
    <script src="{{ asset('assets/plugins/fancybox/source/jquery.fancybox.pack.js') }}"></script>

    <script src="{{ asset('assets/plugins/redactor/redactor.min.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('assets/plugins/redactor/redactor.css') }}">
    <script src="{{ asset('assets/plugins/redactor/lang/es.js') }}"></script>
    <script src="{{ asset('assets/plugins/redactor/plugins/read-more-plugin.js') }}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            if($('.redactor').length){
                $('.redactor').redactor({
                    minHeight: 400,
                    lang: 'es',
                    plugins: ['leermas']
                });
            }

            $('#p_foto').awesomeCropper({
                width: 1600,
                height: 215
            });
            $('#p_menu').awesomeCropper({
                width: 250,
                height: 250
            });
        });
        $(function(){
            if($().fancybox){
                $(".fancybox").fancybox({
                    groupAttr: 'data-rel',
                    prevEffect: 'fade',
                    nextEffect: 'fade',
                    openEffect  : 'elastic',
                    closeEffect  : 'fade',
                    closeBtn: true,
                    helpers: {
                        title: {
                            type: 'float'
                        }
                    }
                });
            }
        });
    </script>
@stop

resources/views/_back/labels/index.blade.php
@extends('_layouts/inicio')

@section ('body')

<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Categorías</h1>
    </div>
</div>
<div class="container content profile">
    <div class="row">
        <div class="col-md-12">
            <a href="{{route('back.labels.create')}}" 
               class="btn btn-warning btn-lg" role="button">
                Crear categoría
            </a>
        </div>     
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-8">
            <table class="table" id="tabla">
                <thead>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Padre</th>
                    <th>Categoria</th>
                    <th>¿Keywords?</th>
                    <th>¿Descripción?</th>
                    <th>Acciones</th>
                </thead>
                <tbody>
                    @foreach($all as $label)
                        <tr>
                            <td>{{ $label->id }}</td>
                            <td>{{ $label->name }}</td>
                            <td>{{ $label->labels_id != null ? $label->label->name : "" }}</td>
                            <td>{{ $label->category }}</td>
                            <td>{{ $label->seo_keywords != null ? 'Sí' : 'No' }}</td>
                            <td>{{ $label->seo_description != null ? 'Sí' : 'No' }}</td>
                            <td>
                                <a href="{{ route('back.labels.show', array('id' => $label->id)) }}" 
                                   class="btn btn-primary btn-sm pull-left" role="button">
                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                </a>
                                <form action="{{ route('back.labels.destroy', [$label->id]) }}" method="POST" 
                                    onsubmit="if(!confirm('¿Estás seguro de querer borrar la categoría?')) return false"
                                    class="col-md-4">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-danger btn-sm" type="submit">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            @include('_layouts.messages', array('errors' => $errors))
            <div id="jstree">
                <ul>
                    @foreach($query as $label1)
                        <li id="{{ $label1->id }}">
                            {{ $label1->name }} 
                            @foreach($label1->labels as $label2)
                                <ul>
                                    <li id="{{ $label2->id }}">
                                        {{ $label2->name }}
                                        @foreach($label2->labels as $label3)
                                            <ul>
                                                <li id="{{ $label3->id }}">
                                                    {{ $label3->name }}
                                                </li>
                                            </ul>
                                        @endforeach
                                    </li>
                                </ul>
                            @endforeach
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>     
    </div>
</div>

@stop

@section ('assets_end')
    <link rel="stylesheet" href="{{ asset('assets/plugins/jstree/themes/default/style.css') }}" />
    <script src="{{ asset('assets/plugins/jstree/jstree.js') }}"></script>

    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/datatables.min.css') }}">
    <script src="{{ asset('assets/plugins/datatables/datatables.min.js') }}"></script>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla').DataTable({
                "language": {
                    "url": ARNY.baseUrl + "/assets/plugins/datatables/spanish.lang"
                },
                stateSave: true
            });
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $('#jstree').on('changed.jstree', function (e, data) {
                for(var i = 0; i < data.selected.length; i++) {
                    $('#tabla').DataTable().search( data.instance.get_node(data.selected[i]).id ).draw();
                }
                
            }).jstree({
                "core" : {
                    "multiple" : false
                }
            }); 

            $('#jstree').on('ready.jstree', function() {
                $(this).jstree("open_all");          
            });
        });
    </script>
@stop